exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache

navigation_header:
- title: Home
url: /
- title: iOS
url: /ios-index
  
plugins:
    - jekyll-remote-theme


navigation_footer:
- title: Created by David Darnes
  url: http://bzcat.fun

remote_theme: daviddarnes/alembic@main

theme: jekyll-theme-cayman